baseURL = 'https://theminiceo.ir'
defaultContentLanguage = 'fa'
title = 'TheMiniCEO'
theme = 'hextra'

[languages]
  [languages.fa]
    languageCode = 'fa-ir'
    languageDirection = 'rtl'
    languageName = 'فارسی'
    title = 'TheMiniCEO'

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

relativeURLs = false